PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Shiba (
  id INTEGER PRIMARY KEY ASC,
  bonkId INTEGER,
  info VARCHAR(5),

  FOREIGN KEY (bonkId) REFERENCES Bonk(id)

);

CREATE TABLE IF NOT EXISTS Bonk (
  id INTEGER PRIMARY KEY ASC,
  info VARCHAR(40) UNIQUE
);
