const {createReadStream} = require("fs")
const through = require("through2")

console.log(process.argv)

// THIS IS GOING TO BE TRANSFORM FUNCTION
// WE WANT TO DEFINE FUNCTION WIH WILL DO UPPERCASE ON
// A CHARACTER

// FUNCTION WILL BE A PARAMETER OF THE through
// FUNCTION, WHUCH WILL CREATE A TRAANSFORM STREAM FOR THE CHUNKS
const writeToUppercase = (chunkBuffer, bufferEncoding, next ) => {
 
    // FIRST ARGUMENT IS ERROR (WE PASSED null FOR THAT)
    // SECOND ARGUMENT IS CHUNK OF DATA FOR WHICH WE DEFINE
    // TRANSFORMATION TO UPPERCASE
    next(null, chunkBuffer.toString().toUpperCase())
}


// SO WE TAKE THE CONTENT OF THIS FILE AND CREATE READABLE STREAM
// FROM HIM
// PAY ATTENTION HERE WE USED item 2 (MEANS WE ARE GOING TO NEED TO PASS
// PATH TO THE FILE WHEN STARTING A FILE)
createReadStream(process.argv[2])
// WE CREATE TRANSFORMATIONS STREM TO DO SOME TRANSFORMATION ON A
// CHUNK
.pipe(through(writeToUppercase))
// THAN, AS WE ALSO DID EARLIER, WE CAN "SPILL CHUNK" IN A STANDARRD
// OUT WRITABLE STREAM
.pipe(process.stdout)

// WHEN WE RUN THIS FILE; CONTENT OF THE FILE SHOULD BE
// PRINTED OUT, BUT EVERY CHRACTER SHOULD BE IN UPPER CASE
