// THIS FUNCTION PRODUCES TRANSITION STREAM
const {createHash} = require("crypto");

// WE CAN USE STANDARD IN AND PIPE IT TO THE HASH STREAM, AND PIPE THAT AGAIN TO STANDATRD OUT
// TO PRINT OUT HASH

// REMEMBER THAT YOU CAN CHANGE EMCODING OF HASH
// IT IS BINARY BE DEFAULT
// I WANT HEX

process.stdin
  .pipe(createHash("sha256", {encoding: "hex"}))
  .pipe(process.stdout);


